apiVersion: v1
kind: ResourceQuota
metadata:
  name: hls-standard-pool
  namespace: arc-runners-standard
spec:
  hard:
    pods: "8"
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "8"
    limits.memory: 16Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: hls-builder-pool
  namespace: arc-runners-builder
spec:
  hard:
    pods: "4"
    requests.cpu: "64"
    requests.memory: 40Gi
    limits.cpu: "64"
    limits.memory: 40Gi
