apiVersion: v1
kind: ServiceAccount
metadata:
  name: hls-standard-runner
  namespace: arc-runners-standard
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hls-builder-runner
  namespace: arc-runners-builder
automountServiceAccountToken: false
