name: Setup Node with retry
inputs:
  node-version: { required: true }
  cache: { default: "" }
  cache-dependency-path: { default: "" }
  mirror: { default: "" }
runs:
  using: composite
  steps:
    - id: first
      continue-on-error: true
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        mirror: ${{ inputs.mirror }}
    - if: steps.first.outcome == 'failure'
      shell: bash
      run: sleep 5
    - if: steps.first.outcome == 'failure'
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        mirror: ${{ inputs.mirror }}
